export enum UserStatus {
  ACTIVE = "ACTIVE",
  PENDING_VERIFICATION = "PENDING_VERIFICATION",
  LIMITED = "LIMITED",
  UNDER_INVESTIGATION = "UNDER_INVESTIGATION",
  TEMPORARILY_SUSPENDED = "TEMPORARILY_SUSPENDED",
  PERMANENTLY_SUSPENDED = "PERMANENTLY_SUSPENDED",
  DEACTIVATED = "DEACTIVATED",
  DELETED = "DELETED"
}

export enum ListingStatus {
  DRAFT = "DRAFT",
  SUBMITTED = "SUBMITTED",
  PENDING_REVIEW = "PENDING_REVIEW",
  UNDER_REVIEW = "UNDER_REVIEW",
  CHANGES_REQUIRED = "CHANGES_REQUIRED",
  APPROVED = "APPROVED",
  ACTIVE = "ACTIVE",
  PAUSED = "PAUSED",
  REJECTED = "REJECTED",
  REPORTED = "REPORTED",
  UNDER_INVESTIGATION = "UNDER_INVESTIGATION",
  REMOVED = "REMOVED",
  EXPIRED = "EXPIRED",
  SOLD = "SOLD",
  ARCHIVED = "ARCHIVED"
}

export enum StoreStatus {
  DRAFT = "DRAFT",
  SUBMITTED = "SUBMITTED",
  UNDER_REVIEW = "UNDER_REVIEW",
  CHANGES_REQUIRED = "CHANGES_REQUIRED",
  APPROVED = "APPROVED",
  ACTIVE = "ACTIVE",
  PAUSED = "PAUSED",
  REJECTED = "REJECTED",
  SUSPENDED = "SUSPENDED",
  ARCHIVED = "ARCHIVED"
}

export enum CampaignStatus {
  DRAFT = "DRAFT",
  PAYMENT_PENDING = "PAYMENT_PENDING",
  SUBMITTED = "SUBMITTED",
  UNDER_REVIEW = "UNDER_REVIEW",
  CHANGES_REQUIRED = "CHANGES_REQUIRED",
  APPROVED = "APPROVED",
  SCHEDULED = "SCHEDULED",
  ACTIVE = "ACTIVE",
  PAUSED = "PAUSED",
  REJECTED = "REJECTED",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED"
}

export enum OfferStatus {
  PENDING = "PENDING",
  COUNTERED = "COUNTERED",
  ACCEPTED = "ACCEPTED",
  DECLINED = "DECLINED",
  EXPIRED = "EXPIRED",
  CANCELLED = "CANCELLED"
}

export enum SafetyPriority {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL"
}

export enum SupportPriority {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  URGENT = "URGENT"
}

export enum SupportStatus {
  OPEN = "OPEN",
  ASSIGNED = "ASSIGNED",
  IN_PROGRESS = "IN_PROGRESS",
  WAITING_USER = "WAITING_USER",
  ESCALATED = "ESCALATED",
  RESOLVED = "RESOLVED",
  CLOSED = "CLOSED",
  REOPENED = "REOPENED"
}
